### ISSUE TITLE
Solvers

### ISSUE THREAD

**Issue by itsdmd** [itsdmd/CS300-MidtermProject#4]
[modules/solver.py](https://github.com/itsdmd/CS300-MidtermProject/blob/main/modules/solver.py)
- [x] `bfs()`
- [x] `dfs()`
- [x] `astar()`
- [x] `ucs()`
- [x] `greedy()`

**Comment by ngynbngoc** [comment]
`bfs()`, `dfs()`, `ucs()`

**Comment by itsdmd** [comment]
`astar()`, `greedy()`

**Comment by itsdmd** [comment]
7b2156c30b4371dbfe9343e6167b2584d3bb65eb
